### ISSUE TITLE
invalid json, trailing comma,

### ISSUE THREAD

**Issue by colin-combe** [Rappsilber-Laboratory/xiAnnotator#24]
https://github.com/Rappsilber-Laboratory/xiSPEC_spectrumViewer/issues/65
is caused by trailing commas in the json output from validator, we think

```
{
	"annotation": {
		"xiVersion": "1.7.6.9.beta",
		"annotatorVersion": "1.4.32",
		"fragmentTolerance": {
			"tolerance": 5.0,
			"unit": "ppm"
		},
		"modifications": [{
				"aminoAcids": ["S", "T", "Y", "K"],
				"id": "(82.04)",
				"mass": 82.0418648
			}, /*HERE*/

		],
		"losses": [{
```

**Comment by colin-combe** [comment]
(@lutzfischer )

**Comment by lutzfischer** [comment]
should be fixed

**Comment by colin-combe** [comment]
its not fixed?
this is json for matched spectrum supporting the link between ELP1 and ELP5 in https://xiview.org/xi3/network.php?upload=18553-39120-70447-08655-99434

```
{
	"annotation": {
		"xiVersion": "1.7.6.9.beta",
		"annotatorVersion": "1.4.33",
		"fragmentTolerance": {
			"tolerance": 5.0,
			"unit": "ppm"
		},
		"modifications": [{
				"aminoAcids": ["S", "T", "Y", "K"],
				"id": "(100.05)",
				"mass": 100.05242999999999
			},
			{
				"aminoAcids": ["S", "T", "Y", "K"],
				"id": "(82.04)",
				"mass": 82.04186479999998
			},
			{
				"aminoAcids": ["C"],
				"id": "carbamidomethyl",
				"mass": 57.021466000000004
			},
			{
				"aminoAcids": ["Q", "R", "N"],
				"id": "deamidated",
				"mass": 0.984800000000007
			}, /*HERE*/
		],
		"losses": [{
```
